server:
  port: 10086

spring:
  application:
    name: test-eureka

eureka:
  client:
    register-with-eureka: false  #是否将自己注册到Eureka-Server中，默认的为true
    fetch-registry: false   #是否从Eureka-Server中获取服务注册信息，默认为true

