server:
  port: 10086

spring:
  application:
    name: test-eureka
eureka:
  client:
    register-with-eureka: false  #是否将自己注册到Eureka-Server中，默认的为true
    fetch-registry: false   #是否从Eureka-Server中获取服务注册信息，默认为true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
  server:
    eviction-interval-timer-in-ms: 10000
    delta-retention-timer-interval-in-ms: 10000
    enable-self-preservation: false

