server:
  port: 30086
spring:
  application:
    name: zuul_test
  freemarker:
    charset: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    appname: zuul_test
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    #每间隔2s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 2
    #告诉服务端，如果我5s之内没有给你发心跳，就代表我“死”了，将我踢出掉
    lease-expiration-duration-in-seconds: 5



zuul:
  routes:
    projectA: /projectA/**
    projectB: /projectB/**
  host:
    connect-timeout-millis: 100
    socket-timeout-millis: 100


ribbon:
  ReadTimeout: 5000 #为连接建立后，服务返回值的超时时间。
  ConnectTimeout: 1 #连接建立的超时时间
