server:
  port: 30086
spring:
  application:
    name: zuul_test

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    appname: zuul_test



zuul:
  routes:
    projectA: /projectA/**
  host:
    connect-timeout-millis: 100
    socket-timeout-millis: 100



ribbon:
  ReadTimeout: 100