server:
  port: 20086
  servlet:
    path: /

spring:
  application:
    name: projectA


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
    enabled: true
    #表示从eureka获取注册信息的频率，（Eureka Client缓存的定期更新周期）
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 10
    # a refresh occurs clients will be unregistered from the Eureka server and there might be a brief moment of time
    # where all instance of a given service are not available
    refresh: false
  instance:
    healthCheckUrlPath: ${server.servlet.path}/health
    statusPageUrlPath: ${server.servlet.path}/info
    homePageUrl: ${server.servlet.path}/
    healthcheck:
      enabled: true
    appname: PROJECTA_A
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    #每间隔2s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 2
    #告诉服务端，如果我5s之内没有给你发心跳，就代表我“死”了，将我踢出掉
    lease-expiration-duration-in-seconds: 5



ribbon:
  ReadTimeout: 10000

feign:
  name: projectA
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 50000