server:
  port: 20086
  servlet:
    path: /

spring:
  application:
    name: projectA


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
    enabled: true
    registry-fetch-interval-seconds: 10
  instance:
    healthCheckUrlPath: ${server.servletPath}/health
    statusPageUrlPath: ${server.servletPath}/info
    homePageUrl: ${server.servletPath}/
    healthcheck:
      enabled: true
    appname: PROJECTA_NAME
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20


ribbon:
  ReadTimeout: 10000